apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: sekun20000/myapp:latest
          ports:
            - containerPort: 9098   # 변경
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 9098          # 외부에서 접근할 포트
      targetPort: 9098    # 컨테이너 내부 포트
      nodePort: 30080     # 로컬 NodePort
